# Generated by Django 3.1.4 on 2021-01-16 11:16

import competition.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='predictions',
            field=models.JSONField(validators=[competition.validators.validate_submission_predictions]),
        ),
    ]
