# Generated by Django 3.1.4 on 2020-12-31 15:25

from django.db import migrations, models
import keyboard.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionSwipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace', models.JSONField(validators=[keyboard.validators.validate_trace])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('target_text', models.CharField(max_length=255)),
                ('trace_matches_text', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
