# Generated by Django 3.1.4 on 2020-12-31 15:52

from django.db import migrations, models
import django.db.models.deletion
import keyboard.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionSwipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('mobile', 'mobile'), ('tablet', 'tablet'), ('pc', 'pc'), ('other', 'other')], max_length=16)),
                ('trace', models.JSONField(validators=[keyboard.validators.validate_trace])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('target_text', models.CharField(max_length=255)),
                ('trace_matches_text', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
