# Generated by Django 3.1.4 on 2021-01-03 14:53

from django.db import migrations, models
import django.db.models.deletion
import keyboard.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_user'),
        ('keyboard', '0002_datacollectionswipe_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollectionswipe',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='games.game', validators=[keyboard.validators.validate_game_has_not_expired]),
        ),
    ]
